SELECT TOP (10)
    [Dim_EMSAuditInformation_PK]
      ,[Incident_ID_Internal]
      ,[IncidentHistory_ID_Internal]
      ,[Incident_Number]
      ,[Audit_History_Origin_Type_ID]
      ,[Audit_History_Origin_Type]
      ,[Audit_History_Type_ID]
      ,[Audit_History_Type]
      ,[Audit_History_Entry_Date_Time]
      ,[Audit_History_User_Name]
      ,[CreatedOnDateTime]
      ,[CreatedBy]
      ,[ModifiedOnDateTime]
      ,[ModifiedBy]
      ,[System_ID]
      ,[CreatedOn]
      ,[ModifiedOn]
      ,[Audit_History_Description]
      ,[ExportHistory_ID_Internal]
      ,[ImportHistory_ID_Internal]
      ,[CadDownloadHistory_ID_Internal]
      ,[Fact_Incident_FK]
      ,[Dim_Personnel_FK]
      ,[Personnel_ID_Internal]
  FROM [Elite_DWPortland].[DwEms].[Dim_EMSAuditInformation]

-- WHERE Audit_History_Type like '%fail%'
WHERE
    Audit_History_Description like '%fail%'