SELECT TOP (1000) [Fact_Fire_PK]
      ,[Agency_shortname]
      ,[Basic_Incident_Form_Number]
      ,[Basic_Incident_Validity_Score]

      ,[Incident_ID_Internal]
      ,[Dim_Basic_FK] -- joins [DwFire].[Dim_Basic] ([Dim_Basic_PK])
      ,[Dim_Fire_FK] -- joins [DwFire].[Dim_Fire] ([Dim_Fire_PK])
      ,[Dim_StructureFire_FK] -- joins [DwFire].[Dim_StructureFire] ([Dim_StructureFire_PK])
      ,[Dim_Arson_FK] -- joins [DwFire].[Dim_Arson] ([Dim_Arson_PK])
      ,[Dim_Wildland_FK] -- joins [DwFire].[Dim_Wildland] ([Dim_Wildland_PK])
      ,[Agency_ID_Internal]
      ,[Dim_Agency_FK] -- joins [DwEms].[Dim_Agency] ([Dim_Agency_PK])
      ,[Dim_Date_Fire_PK] -- joins [dbo].[DSV_Dim_Incident_Date_Fire] ([Dim_Incident_Date_Fire_FK])
      ,[Dim_TimeOfDay_Fire_PK] -- joins [dbo].[DSV_Dim_Incident_Time_Of_Day_Fire] ([Dim_Incident_Time_Of_Day_Fire_PK])
      ,[CAD_ID_FK] -- joins [DwFire].[Dim_Fire_CAD] ([Dim_Fire_CAD_PK])
      ,[CAD_Incident_ID_Internal]
      ,[CAD_ID1_FK] -- no explicit join in datamart_fire.sql
      ,[CAD_Incident_ID1_Internal]
      ,[Dim_FireSupplementalQuestions_FK] -- no explicit join in datamart_fire.sql
      ,[Dim_FireSupplementalQuestions1_FK] -- no explicit join in datamart_fire.sql
      ,[Dim_FireSupplementalQuestions2_FK] -- no explicit join in datamart_fire.sql
      ,[FirstApparatusArrived_Dim_ApparatusResources_FK] -- joins [DwFire].[Dim_ApparatusResources] ([Dim_ApparatusResources_PK])

      ,[Basic_Apparatus_Or_Personnel_Module_Used]
      ,[Basic_Number_Of_Contract_Response]
      ,[Basic_Number_Of_EMS_Apparatus]
      ,[Basic_Number_Of_EMS_Personnel]
      ,[Basic_Number_Of_Incident_Address_Override]
      ,[Basic_Number_Of_Other_Apparatus]
      ,[Basic_Number_Of_Other_Personnel]
      ,[Basic_Number_Of_Suppression_Apparatus]
      ,[Basic_Number_Of_Suppression_Personnel]
      ,[Basic_Incident_Total_Number_of_People_Assembled_at_Arrival]

      -- Losses
      ,[Basic_Incident_Total_Losses]
      ,[Basic_Property_Losses_With_Not_Value]
      ,[Basic_Content_Losses_NotValue]
      ,[Basic_Property_Pre_Incident_Value_NotValue]
      ,[Basic_Contents_Pre_Incident_Value_NotValue]
      ,[Basic_Civilian_Casualty_Count]
      ,[Basic_Civilian_Injuries_Count]
      ,[Basic_Content_Losses]
      ,[Basic_Contents_Pre_Incident_Value]
      ,[Basic_Fire_Service_Casualty_Count]

      ,[Basic_Incident_Civilian_Deaths_Count]
      ,[Basic_Incident_Fire_Service_Injuries_Count]
      ,[Basic_Incident_Hazardouse_Materials_Count]
      ,[Basic_Incident_Patient_Count]
      ,[Basic_Incident_Service_Deaths_Count]
      ,[Basic_Property_Losses]
      ,[Basic_Property_Pre_Incident_Value]
      ,[Basic_Incident_Days_To_Enter_Incident]

      ,[Fire_Acres_Burned]
      ,[Fire_Estimated_Age_Of_Person_Involved_In_Years]
      ,[Fire_Estimated_Number_Of_Residential_Units]
      ,[Fire_Number_Of_Buildings_Involved]
      ,[Fire_Number_Of_Likely_Youth]
      ,[Fire_Service_Casualty_Number_Of_Primary_Responses_During_Past_24_Hours]
    
      ,[HazMat_Civilian_Casualties_Deaths]
      ,[HazMat_Civilian_Casualties_Injuries]
      ,[HazMat_Civilian_Other_Deaths]
      ,[HazMat_Civilian_Other_Injuries]
      ,[HazMat_Estimated_Number_Of_Buildings_Evacuated]
      ,[HazMat_Estimated_Number_Of_People_Evacuated]
      ,[HazMat_Fire_Service_Exposure_Deaths]
      ,[HazMat_Fire_Service_Exposure_Injuries]
      ,[HazMat_Fire_Service_Other_Deaths]
      ,[HazMat_Fire_Service_Other_Injuries]
      ,[HazMat_Hazardous_Materials_Count]
      ,[HazMat_Number_Of_Entries_Made_By_Emergency_Personnel_To_Contain_Spill_Or_Leak]

      ,[Structure_Fire_Main_Floor_Length_In_Feet]
      ,[Structure_Fire_Main_Floor_Total_Square_Feet]
      ,[Structure_Fire_Main_Floor_Width_In_Feet]
      ,[Structure_Fire_Number_Of_Sprinkler_Heads_Operating]
      ,[Structure_Fire_Number_Of_Stories_With_Extreme_Damage]
      ,[Structure_Fire_Number_Of_Stories_With_Heavy_Damage]
      ,[Structure_Fire_Number_Of_Stories_With_Minor_Damage]
      ,[Structure_Fire_Number_Of_Stories_With_Significant_Damage]
      ,[Structure_Fire_Story_Of_Fire_Origin]
      ,[Structure_Fire_Total_Number_Of_Stories_At_Or_Above_Grade]
      ,[Structure_Fire_Total_Number_Of_Stories_Below_Grade]

      -- Target times (these are not used, but are included for completeness)
      ,[Basic_Incident_Total_Time_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_In_Seconds]
      ,[Basic_Incident_Alarm_To_Controlled_In_Minutes]
      ,[Basic_Incident_Alarm_To_Controlled_In_Seconds]
      ,[Basic_Incident_Alarm_To_First_Unit_Arrived_In_Minutes]
      ,[Basic_Incident_Alarm_To_First_Unit_Arrived_In_Seconds]
      ,[Basic_Incident_Alarm_To_In_Service_Minutes]
      ,[Basic_Incident_Alarm_To_In_Service_Seconds]
      ,[Basic_Incident_Alarm_To_Last_Unit_Arrived_In_Minutes]
      ,[Basic_Incident_Alarm_To_Last_Unit_Arrived_In_Seconds]
      ,[Basic_Incident_Alarm_To_Last_Unit_Cleared_Minutes]
      ,[Basic_Incident_Alarm_To_Last_Unit_Cleared_Seconds]
      ,[Basic_Incident_Arrival_To_Controlled_Minutes]
      ,[Basic_Incident_Arrival_To_Controlled_Seconds]
      ,[Basic_Incident_Arrival_To_In_Service_Minutes]
      ,[Basic_Incident_Arrival_To_In_Service_Seconds]
      ,[Basic_Incident_Arrival_To_Last_Unit_Cleared_Minutes]
      ,[Basic_Incident_Arrival_To_Last_Unit_Cleared_Seconds]
      ,[Basic_Incident_Controlled_To_In_Service_Minutes]
      ,[Basic_Incident_Controlled_To_In_Service_Seconds]
      ,[Basic_Incident_Controlled_To_Last_Unit_Cleared_Minutes]
      ,[Basic_Incident_Controlled_To_Last_Unit_Cleared_Seconds]
      ,[Basic_Incident_PSAP_To_Alarm_In_Minutes]
      ,[Basic_Incident_PSAP_To_Alarm_In_Seconds]
      ,[Basic_Incident_PSAP_To_Arrival_In_Minutes]
      ,[Basic_Incident_PSAP_To_Arrival_In_Seconds]
      ,[Basic_Incident_PSAP_To_Controlled_In_Minutes]
      ,[Basic_Incident_PSAP_To_Controlled_In_Seconds]
      ,[Basic_Incident_PSAP_To_Last_Unit_Cleared_In_Minutes]
      ,[Basic_Incident_PSAP_To_Last_Unit_Cleared_In_Seconds]
      ,[Basic_Incident_Alarm_To_Arrival_Meets_Target]
      ,[Basic_Incident_Alarm_To_Controlled_Meets_Target]
      ,[Basic_Incident_Alarm_To_In_Service_Meets_Target]
      ,[Basic_Incident_Alarm_To_Last_Unit_Cleared_Meets_Target]
      ,[Basic_Incident_Arrival_To_Controlled_Meets_Target]
      ,[Basic_Incident_Arrival_To_In_Service_Meets_Target]
      ,[Basic_Incident_Arrival_To_Last_Unit_Cleared_Meets_Target]
      ,[Basic_Incident_Controlled_To_In_Service_Meets_Target]
      ,[Basic_Incident_Controlled_To_Last_Unit_Cleared_Meets_Target]
      ,[Basic_Incident_PSAP_To_Alarm_Meets_Target]
      ,[Basic_Incident_PSAP_To_Arrival_Meets_Target]
      ,[Basic_Incident_PSAP_To_Controlled_Meets_Target]
      ,[Basic_Incident_PSAP_To_Last_Unit_Cleared_Meets_Target]
      ,[Basic_Incident_PSAP_to_Left_Scene_Time_Meets_Target]
      ,[Basic_Incident_PSAP_to_Arrived_at_Hospital_Meets_Target]
      ,[Basic_Incident_PSAP_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_Alarm_to_Left_Scene_Meets_Target]
      ,[Basic_Incident_Alarm_to_Arrived_at_Hospital_Meets_Target]
      ,[Basic_Incident_Alarm_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_Arrived_at_Scene_to_Left_Scene_Meets_Target]
      ,[Basic_Incident_Arrived_at_Scene_to_Arrived_at_Hospital_Meets_Target]
      ,[Basic_Incident_Arrived_at_Scene_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_Controlled_to_Left_Scene_Meets_Target]
      ,[Basic_Incident_Controlled_to_Arrived_at_Hospital_Meets_Target]
      ,[Basic_Incident_Controlled_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_Left_Scene_to_Arrived_at_Hospital_Meets_Target]
      ,[Basic_Incident_Left_Scene_to_Last_Unit_Cleared_Meets_Target]
      ,[Basic_Incident_Left_Scene_to_In_Service_Meets_Target]
      ,[Basic_Incident_Left_Scene_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_Arrived_at_Hospital_to_Last_Unit_Cleared_Meets_Target]
      ,[Basic_Incident_Arrived_at_Hospital_to_In_Service_Meets_Target]
      ,[Basic_Incident_Arrived_at_Hospital_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_Last_Unit_Cleared_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_In_Service_to_In_Quarters_Meets_Target]
      ,[Basic_Incident_Alarm_To_First_Unit_Arrived_Meets_Target]
      ,[Basic_Incident_Alarm_To_Last_Unit_Arrived_Meets_Target]
      ,[Basic_Incident_Alarm_To_Arrival_Of_17_Personnel_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_18_Personnel_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_19_Personnel_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_20_Personnel_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_21_Personnel_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_22_Personnel_In_Minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_23_Personnel_In_Minutes]
      ,[Basic_Incident_Alarm_to_Arrival_of_24_Personnel_in_Minutes]
      ,[Basic_Incident_Alarm_to_Arrival_of_25_Personnel_in_Minutes]
      ,[Basic_Incident_Alarm_to_Arrival_of_26_Personnel_in_Minutes]
      ,[Basic_Incident_First_Unit_Arrived_Dispatch_To_Arrival_In_Minutes]
      ,[Basic_Incident_First_Unit_Arrived_Dispatch_To_En_Route_In_Minutes]
      ,[Basic_Incident_First_Unit_Arrived_En_Route_To_Arrival_In_Minutes]
      ,[Basic_Incident_First_Unit_Arrived_Dispatch_To_Arrival_In_Seconds]
      ,[Basic_Incident_First_Unit_Arrived_Dispatch_To_En_Route_In_Seconds]
      ,[Basic_Incident_First_Unit_Arrived_En_Route_To_Arrival_In_Seconds]
      ,[Basic_Incident_PSAP_to_Left_Scene_Time_in_Minutes]
      ,[Basic_Incident_PSAP_to_Arrived_at_Hospital_in_Minutes]
      ,[Basic_Incident_PSAP_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_Alarm_to_Left_Scene_in_Minutes]
      ,[Basic_Incident_Alarm_to_Arrived_at_Hospital_in_Minutes]
      ,[Basic_Incident_Alarm_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_Arrived_at_Scene_to_Left_Scene_in_Minutes]
      ,[Basic_Incident_Arrived_at_Scene_to_Arrived_at_Hospital_in_Minutes]
      ,[Basic_Incident_Arrived_at_Scene_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_Controlled_to_Left_Scene_in_Minutes]
      ,[Basic_Incident_Controlled_to_Arrived_at_Hospital_in_Minutes]
      ,[Basic_Incident_Controlled_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_Left_Scene_to_Arrived_at_Hospital_in_Minutes]
      ,[Basic_Incident_Left_Scene_to_Last_Unit_Cleared_in_Minutes]
      ,[Basic_Incident_Left_Scene_to_In_Service_in_Minutes]
      ,[Basic_Incident_Left_Scene_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_Arrived_at_Hospital_to_Last_Unit_Cleared_in_Minutes]
      ,[Basic_Incident_Arrived_at_Hospital_to_In_Service_in_Minutes]
      ,[Basic_Incident_Arrived_at_Hospital_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_Last_Unit_Cleared_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_In_Service_to_In_Quarters_in_Minutes]
      ,[Basic_Incident_PSAP_to_Left_Scene_Time_in_Seconds]
      ,[Basic_Incident_PSAP_to_Arrived_at_Hospital_in_Seconds]
      ,[Basic_Incident_PSAP_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_Alarm_to_Left_Scene_in_Seconds]
      ,[Basic_Incident_Alarm_to_Arrived_at_Hospital_in_Seconds]
      ,[Basic_Incident_Alarm_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_Arrived_at_Scene_to_Left_Scene_in_Seconds]
      ,[Basic_Incident_Arrived_at_Scene_to_Arrived_at_Hospital_in_Seconds]
      ,[Basic_Incident_Arrived_at_Scene_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_Controlled_to_Left_Scene_in_Seconds]
      ,[Basic_Incident_Controlled_to_Arrived_at_Hospital_in_Seconds]
      ,[Basic_Incident_Controlled_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_Left_Scene_to_Arrived_at_Hospital_in_Seconds]
      ,[Basic_Incident_Left_Scene_to_Last_Unit_Cleared_in_Seconds]
      ,[Basic_Incident_Left_Scene_to_In_Service_in_Seconds]
      ,[Basic_Incident_Left_Scene_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_Arrived_at_Hospital_to_Last_Unit_Cleared_in_Seconds]
      ,[Basic_Incident_Arrived_at_Hospital_to_In_Service_in_Seconds]
      ,[Basic_Incident_Arrived_at_Hospital_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_Last_Unit_Cleared_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_In_Service_to_In_Quarters_in_Seconds]
      ,[Basic_Incident_Alarm_To_Arrival_Of_1_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_2_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_3_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_4_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_5_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_6_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_7_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_8_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_9_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_10_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_11_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_12_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_13_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_14_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_15_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_Of_16_Personnel_In_minutes]
      ,[Basic_Incident_Alarm_To_Arrival_In_Whole_Minutes]
      ,[Basic_Incident_PSAP_To_Alarm_In_Whole_Minutes]
      ,[Basic_Incident_PSAP_To_Arrival_In_Whole_Minutes]
      ,[Basic_Incident_PSAP_To_Controlled_In_Whole_Minutes]
      ,[Basic_Incident_PSAP_To_Left_Scene_Time_In_Whole_Minutes]
      ,[Basic_Incident_PSAP_To_Arrived_At_Hospital_In_Whole_Minutes]
      ,[Basic_Incident_PSAP_To_Last_Unit_Cleared_In_Whole_Minutes]
      ,[Basic_Incident_PSAP_To_In_Quarters_In_Whole_Minutes]
      ,[Basic_Incident_Controlled_To_Arrived_At_Hospital_In_Whole_Minutes]
      ,[Basic_Incident_Controlled_To_In_Service_In_Whole_Minutes]
      ,[Basic_Incident_Controlled_To_Last_Unit_Cleared_In_Whole_Minutes]
      ,[Basic_Incident_Controlled_To_In_Quarters_In_Whole_Minutes]
      ,[Basic_Incident_Arrival_To_Controlled_In_Whole_Minutes]
      ,[Basic_Incident_Arrival_To_In_Service_In_Whole_Minutes]
      ,[Basic_Incident_Arrival_To_Last_Unit_Cleared_In_Whole_Minutes]
      ,[Basic_Incident_Last_Unit_Cleared_To_In_Quarters_In_Whole_Minutes]
      ,[EMS_Arrived_At_Patient_To_Patient_Transfer_In_Minutes]


      -- System
    --   ,[System_ID] -- IGNORE
      ,[CreatedOn]
      ,[ModifiedOn]

  FROM [Elite_DWPortland].[DwFire].[Fact_Fire]