SELECT TOP (1000)
    [Dim_Agency_PK]

      ,[Agency_ID_Internal]
        -- "6dc7ba46-6723-eb11-a95e-001dd8b72424 for "Portland Fire & Rescue - EMS"
        -- "e409caa9-3b4e-43f0-ac25-64b11d2ea38b" for "Training/ Testing Agency"

      ,[Agency_Name]

    --   ,[Agency_Unique_State_ID]
    --   ,[Agency_Number]
    --   ,[Agency_State]
    --   ,[Agency_Service_Area_State_List]
    --   ,[Agency_Primary_Type_Of_Service]
    --   ,[Agency_Level_Of_Service]
    --   ,[Agency_Organziation_Status]
    --   ,[Agency_Organizational_Type]
    --   ,[Agency_Organizational_Tax_Status]
    --   ,[Agency_Other_Types_Of_Service_List]
    --   ,[Agency_National_Provider_Identifier_List]
    --   ,[Agency_Fire_Department_ID_Number_List]
    --   ,[Agency_Time_Zone]
    --   ,[Agency_Daylight_Savings_Time_Use]
    --   ,[Agency_Level1]
    --   ,[Agency_Level2]
    --   ,[Agency_Level3]
    --   ,[Agency_Level4]
    --   ,[AgencyID_Level1_Internal]
    --   ,[AgencyID_Level2_Internal]
    --   ,[AgencyID_Level3_Internal]
    --   ,[AgencyID_Level4_Internal]
    --   ,[DeletedStatus]
    --   ,[Agency_Urbanicity]
    --   ,[Agency_County_Population_2010]
    --   ,[Agency_Urban_Influence_Code]
    --   ,[Agency_Urban_Influence_Description]
    --   ,[Agency_County_Total_Area_In_Square_Miles]
    --   ,[Agency_FDID]
    --   ,[Agency_State_Name_Reporting_To]
    --   ,[Agency_Active_Status]
    --   ,[Agency_Is_Demo_Service]
    --   ,[Agency_Has_EMS_CAD_Integration]
    --   ,[Agency_Has_Fire_CAD_Integration]
    --   ,[Agency_Critical_Care_Flag]
    --   ,[Agency_Default_Ems_Print_Report_ID]
    --   ,[Agency_Default_Community_Health_Print_Report_ID]
    --   ,[Agency_Default_Fire_Print_Report_ID]
    --   ,[IsParent]
    --   ,[Agency_HL7_OID]
    --   ,[AgencyID_Level5_Internal]
    --   ,[Agency_Level5]
    --   ,[Agency_EMS_Flag]
    --   ,[Agency_Fire_Flag]
    --   ,[Reporting_Standard_ID]
    --   ,[Reporting_Standard]
    --   ,[Agency_Global_Identifier]

    --   ,[System_ID] -- IGNORE - not used
      ,[CreatedOn]
      ,[ModifiedOn]

  FROM [Elite_DWPortland].[DwEms].[Dim_Agency]